FROM node:4.6

ADD ["./package.json", "/arithmancy/package.json"]
WORKDIR /arithmancy

RUN npm install

RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /wait.sh
RUN chmod +x /wait.sh

ADD [".", "/arithmancy"]

CMD dockerize -wait tcp://db:5432

CMD /wait.sh $RABBITMQ_HOSTNAME:5672 -t 30 && /wait.sh $POSTGRES_HOSTNAME:5432 -t 30 && npm run test
